FROM python:3.9-alpine

WORKDIR /app

COPY client.py /app/client.py

RUN apk update && \
    apk --no-cache add gcc musl-dev libffi-dev openssl-dev && \
    pip install --upgrade pip

CMD ["python", "/app/client.py"]